// <auto-generated />
namespace BillsManagementWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductCateogyr_NewFields_Color_MonthBudget : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductCateogyr_NewFields_Color_MonthBudget));
        
        string IMigrationMetadata.Id
        {
            get { return "201705181746470_ProductCateogyr_NewFields_Color_MonthBudget"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
